const ADD_MARKER = 'ADD_MARKER'
const UPDATE_MARKER = 'UPDATE_MARKER'
const DELETE_MARKER = 'DELETE_MARKER'
const ACTIVE_MARKERS = 'ACTIVE_MARKERS'

module.exports = {
  ADD_MARKER,
  UPDATE_MARKER,
  DELETE_MARKER,
  ACTIVE_MARKERS
}
